#include "cli.h"
#include "utils/apk_patcher.h"
#include "utils/file_utils.h"
#include "utils/inject_profile.h"
#include "utils/payload_archive.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void print_inject_help(void) {
    puts("Usage: fpatch inject --source <app.apk> [options]");
    puts("       fpatch inject --profile <profile.json|profile.yaml> [options]");
    puts("");
    puts("Patches and resigns an APK supplied for authorized development or security testing.");
    puts("");
    puts("Inputs:");
    puts("  --source, --apk <file>      Base APK (CLI values override the profile).");
    puts("  --profile <file>            JSON or YAML injection profile.");
    puts("  --native <file.so>          Native library; repeatable, ABI inferred from ELF.");
    puts("  --native-init <lib=symbol>  Initializer for a native library; repeatable.");
    puts("  --native-module <lib=name>  Lua require name for a native extension.");
    puts("  --lua <file.lua>            Embedded require-able Lua module; repeatable.");
    puts("  --lua-entry <file.lua>      Embedded Lua startup script; repeatable.");
    puts("  --asset <file>              Ship an asset under assets/falconpatch/user.");
    puts("  --split <file.apk>          Related split APK to resign; repeatable.");
    puts("");
    puts("Patching:");
    puts("  --output <file.apk>         Output base APK (default: <source>-fpatch.apk).");
    puts("  --strategy <name>           auto, provider, or provider-debuggable.");
    puts("  --bootstrap-language <lang> java or kotlin.");
    puts("  --random-libname            Use a random alphabetic runtime library name.");
    puts("  --dry-run                   Parse and summarize inputs without writing an APK.");
    puts("");
    puts("Signing:");
    puts("  --keystore <file>           Signing keystore; a local debug key is generated by default.");
    puts("  --ks-alias <name>           Key alias (default: androiddebugkey).");
    puts("  --ks-pass <password>        Keystore password (default: android).");
    puts("  --key-pass <password>       Key password (default: android).");
    puts("  --no-sign                   Produce aligned unsigned APKs.");
}

static int set_text(char *destination, size_t size, const char *value,
                    char *error, size_t error_size) {
    if (!value) {
        return 1;
    }
    if (strlen(value) >= size) {
        snprintf(error, error_size, "A command-line value is too long.");
        return 0;
    }
    snprintf(destination, size, "%s", value);
    return 1;
}

static int add_repeated_paths(Command *cmd, const char *flag,
                              FpatchInjectProfile *profile, int kind,
                              char *error, size_t error_size) {
    size_t i;
    size_t count = get_flag_value_count(cmd, flag);
    for (i = 0; i < count; i++) {
        const char *path = get_flag_value_at(cmd, flag, i);
        int added;
        if (kind == 0) {
            added = fpatch_profile_add_native(profile, path, error, error_size);
        } else if (kind == 1) {
            added = fpatch_profile_add_lua(profile, path, 0, error, error_size);
        } else if (kind == 2) {
            added = fpatch_profile_add_lua(profile, path, 1, error, error_size);
        } else if (kind == 3) {
            added = fpatch_profile_add_asset(profile, path, error, error_size);
        } else {
            added = fpatch_profile_add_split(profile, path, error, error_size);
        }
        if (!added) {
            return 0;
        }
    }
    return 1;
}

static int native_matches(const FpatchNativeInput *input, const char *key) {
    char filename[256];
    return strcmp(fpatch_path_basename(input->path), key) == 0 ||
           (fpatch_native_filename(input, filename, sizeof(filename)) &&
            strcmp(filename, key) == 0) ||
           (input->name[0] && strcmp(input->name, key) == 0);
}

static int apply_native_setting(Command *cmd, const char *flag,
                                FpatchInjectProfile *profile, int module,
                                char *error, size_t error_size) {
    size_t i;
    for (i = 0; i < get_flag_value_count(cmd, flag); i++) {
        const char *setting = get_flag_value_at(cmd, flag, i);
        const char *equals = strchr(setting, '=');
        size_t key_size;
        size_t j;
        int matched = 0;
        char key[256];
        if (!equals || equals == setting || !equals[1]) {
            snprintf(error, error_size, "%s expects <library>=<value>.", flag);
            return 0;
        }
        key_size = (size_t)(equals - setting);
        if (key_size >= sizeof(key)) {
            snprintf(error, error_size, "Native library selector is too long.");
            return 0;
        }
        memcpy(key, setting, key_size);
        key[key_size] = '\0';
        for (j = 0; j < profile->native_count; j++) {
            if (native_matches(&profile->native[j], key)) {
                char *destination = module
                    ? profile->native[j].lua_module : profile->native[j].init;
                size_t destination_size = module
                    ? sizeof(profile->native[j].lua_module) : sizeof(profile->native[j].init);
                if (!set_text(destination, destination_size, equals + 1,
                              error, error_size)) {
                    return 0;
                }
                matched = 1;
            }
        }
        if (!matched) {
            snprintf(error, error_size, "%s did not match a native input: %s.", flag, key);
            return 0;
        }
    }
    return 1;
}

static void print_dry_run(const FpatchInjectProfile *profile) {
    puts("Injection plan");
    printf("  Source: %s\n", profile->source);
    printf("  Output: %s\n", profile->output[0] ? profile->output : "derived from source");
    printf("  Strategy: %s\n", profile->strategy);
    printf("  Bootstrap language: %s\n", profile->bootstrap_language);
    printf("  Native libraries: %zu\n", profile->native_count);
    printf("  Lua scripts: %zu\n", profile->lua_count);
    printf("  Assets: %zu\n", profile->asset_count);
    printf("  Split APKs: %zu\n", profile->split_count);
    printf("  Random runtime name: %s\n", profile->random_libname ? "yes" : "no");
    printf("  Signing: %s\n", profile->no_sign ? "disabled" : "enabled");
}

static int merge_command_line(Command *cmd, FpatchInjectProfile *profile,
                              char *error, size_t error_size) {
    const char *source = get_flag_value(cmd, "--source");
    const char *apk = get_flag_value(cmd, "--apk");
    if (source && apk) {
        snprintf(error, error_size, "Use either --source or --apk, not both.");
        return 0;
    }
    if (!set_text(profile->source, sizeof(profile->source), source ? source : apk,
                  error, error_size) ||
        !set_text(profile->output, sizeof(profile->output), get_flag_value(cmd, "--output"),
                  error, error_size) ||
        !set_text(profile->strategy, sizeof(profile->strategy), get_flag_value(cmd, "--strategy"),
                  error, error_size) ||
        !set_text(profile->bootstrap_language, sizeof(profile->bootstrap_language),
                  get_flag_value(cmd, "--bootstrap-language"), error, error_size) ||
        !set_text(profile->keystore, sizeof(profile->keystore), get_flag_value(cmd, "--keystore"),
                  error, error_size) ||
        !set_text(profile->key_alias, sizeof(profile->key_alias), get_flag_value(cmd, "--ks-alias"),
                  error, error_size) ||
        !set_text(profile->store_password, sizeof(profile->store_password), get_flag_value(cmd, "--ks-pass"),
                  error, error_size) ||
        !set_text(profile->key_password, sizeof(profile->key_password), get_flag_value(cmd, "--key-pass"),
                  error, error_size)) {
        return 0;
    }
    if (!add_repeated_paths(cmd, "--native", profile, 0, error, error_size) ||
        !add_repeated_paths(cmd, "--lua", profile, 1, error, error_size) ||
        !add_repeated_paths(cmd, "--lua-entry", profile, 2, error, error_size) ||
        !add_repeated_paths(cmd, "--asset", profile, 3, error, error_size) ||
        !add_repeated_paths(cmd, "--split", profile, 4, error, error_size) ||
        !apply_native_setting(cmd, "--native-init", profile, 0, error, error_size) ||
        !apply_native_setting(cmd, "--native-module", profile, 1, error, error_size)) {
        return 0;
    }
    if (has_flag(cmd, "--random-libname")) {
        profile->random_libname = 1;
    }
    if (has_flag(cmd, "--no-sign")) {
        profile->no_sign = 1;
    }
    return 1;
}

static void handle_inject(Command *cmd) {
    FpatchInjectProfile *profile;
    FpatchInjectResult *result;
    char error[1024] = "";
    const char *profile_path;
    size_t i;

    if (has_flag(cmd, "--help")) {
        print_inject_help();
        return;
    }
    profile = (FpatchInjectProfile *)malloc(sizeof(*profile));
    result = (FpatchInjectResult *)calloc(1, sizeof(*result));
    if (!profile || !result) {
        fprintf(stderr, "Error: Out of memory while preparing injection.\n");
        free(profile);
        free(result);
        cmd->exit_code = 1;
        return;
    }
    fpatch_profile_init(profile);
    profile_path = get_flag_value(cmd, "--profile");
    if ((profile_path && !fpatch_profile_load(profile_path, profile, error, sizeof(error))) ||
        !merge_command_line(cmd, profile, error, sizeof(error)) ||
        !fpatch_profile_validate(profile, error, sizeof(error))) {
        fprintf(stderr, "Error: %s\n", error);
        free(profile);
        free(result);
        cmd->exit_code = 1;
        return;
    }
    if (has_flag(cmd, "--dry-run")) {
        print_dry_run(profile);
        free(profile);
        free(result);
        return;
    }
    if (!fpatch_inject_apk(profile, result, error, sizeof(error))) {
        fprintf(stderr, "Error: %s\n", error[0] ? error : "Injection failed.");
        free(profile);
        free(result);
        cmd->exit_code = 1;
        return;
    }

    puts("FalconPatch injection complete");
    printf("  Strategy: %s\n", result->strategy_used);
    printf("  Bootstrap: %s\n", result->bootstrap_language);
    printf("  Runtime library: lib%s.so\n", result->runtime_library);
    printf("  Signing: %s\n", result->resigned ? "resigned and verified" : "unsigned");
    puts("  Outputs:");
    for (i = 0; i < result->output_count; i++) {
        printf("    %s\n", result->output_paths[i]);
    }
    free(profile);
    free(result);
}

CMD_INIT(register_inject_cmd) {
    Command *inject = add_cmd("inject", handle_inject);
    if (inject) {
        set_cmd_description(inject, "Inject native/Lua test modules into an authorized APK.");
        inject->add_flag(inject, "--source", true, true, false)
              ->add_flag(inject, "--apk", true, true, false)
              ->add_flag(inject, "--output", true, true, false)
              ->add_flag(inject, "--profile", true, true, false)
              ->add_flag(inject, "--native", true, true, true)
              ->add_flag(inject, "--native-init", true, true, true)
              ->add_flag(inject, "--native-module", true, true, true)
              ->add_flag(inject, "--lua", true, true, true)
              ->add_flag(inject, "--lua-entry", true, true, true)
              ->add_flag(inject, "--asset", true, true, true)
              ->add_flag(inject, "--split", true, true, true)
              ->add_flag(inject, "--strategy", true, true, false)
              ->add_flag(inject, "--bootstrap-language", true, true, false)
              ->add_flag(inject, "--random-libname", true, false, false)
              ->add_flag(inject, "--keystore", true, true, false)
              ->add_flag(inject, "--ks-alias", true, true, false)
              ->add_flag(inject, "--ks-pass", true, true, false)
              ->add_flag(inject, "--key-pass", true, true, false)
              ->add_flag(inject, "--no-sign", true, false, false)
              ->add_flag(inject, "--dry-run", true, false, false)
              ->add_flag(inject, "--help", true, false, false);
    }
}
