if(NOT DEFINED ROOT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "ROOT and OUTPUT are required")
endif()

get_filename_component(output_directory "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${output_directory}")
file(WRITE "${OUTPUT}" "#include \"utils/embedded_resources.h\"\n\n#include <string.h>\n\n")

set(entries "")
set(resource_index 0)

function(embed_resource kind name relative_path)
    set(symbol "fpatch_resource_${resource_index}" PARENT_SCOPE)
    set(symbol "fpatch_resource_${resource_index}")
    math(EXPR next_index "${resource_index} + 1")
    set(resource_index "${next_index}" PARENT_SCOPE)
    set(path "${ROOT}/${relative_path}")
    if(EXISTS "${path}")
        file(READ "${path}" hex HEX)
        string(LENGTH "${hex}" hex_length)
        math(EXPR byte_length "${hex_length} / 2")
        file(APPEND "${OUTPUT}" "static const unsigned char ${symbol}[] = {\n")
        set(offset 0)
        while(offset LESS hex_length)
            math(EXPR remaining "${hex_length} - ${offset}")
            if(remaining GREATER 64)
                set(chunk_length 64)
            else()
                set(chunk_length "${remaining}")
            endif()
            string(SUBSTRING "${hex}" ${offset} ${chunk_length} chunk)
            string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1," chunk "${chunk}")
            file(APPEND "${OUTPUT}" "    ${chunk}\n")
            math(EXPR offset "${offset} + ${chunk_length}")
        endwhile()
        file(APPEND "${OUTPUT}" "};\n\n")
    else()
        set(byte_length 0)
        file(APPEND "${OUTPUT}" "static const unsigned char ${symbol}[] = {0};\n\n")
    endif()
    set(entry "    {\"${kind}\", \"${name}\", ${symbol}, ${byte_length}},\n")
    set(entries "${entries}${entry}" PARENT_SCOPE)
endfunction()

embed_resource("runtime" "armeabi-v7a" "dist/android/armeabi-v7a/libfalconpatch.so")
embed_resource("runtime" "arm64-v8a" "dist/android/arm64-v8a/libfalconpatch.so")
embed_resource("runtime" "x86" "dist/android/x86/libfalconpatch.so")
embed_resource("runtime" "x86_64" "dist/android/x86_64/libfalconpatch.so")
embed_resource("bootstrap-dex" "java" "dist/android/bootstrap/java/classes.dex")
embed_resource("bootstrap-dex" "kotlin" "dist/android/bootstrap/kotlin/classes.dex")
embed_resource("bootstrap-source" "RuntimeBridge.java" "android/java/dev/falconpatch/runtime/RuntimeBridge.java")
embed_resource("bootstrap-source" "FalconPatchProvider.java" "android/java/dev/falconpatch/runtime/FalconPatchProvider.java")
embed_resource("bootstrap-source" "FalconPatchService.java" "android/java/dev/falconpatch/runtime/FalconPatchService.java")
embed_resource("bootstrap-source" "FalconPatchKotlinProvider.kt" "android/kotlin/dev/falconpatch/runtime/FalconPatchKotlinProvider.kt")
embed_resource("bootstrap-source" "FalconPatchKotlinService.kt" "android/kotlin/dev/falconpatch/runtime/FalconPatchKotlinService.kt")

file(APPEND "${OUTPUT}" "typedef struct {\n    const char *kind;\n    const char *name;\n    const unsigned char *data;\n    size_t size;\n} EmbeddedEntry;\n\n")
file(APPEND "${OUTPUT}" "static const EmbeddedEntry fpatch_resources[] = {\n${entries}};\n\n")
file(APPEND "${OUTPUT}" "FpatchEmbeddedResource fpatch_embedded_find(const char *kind, const char *name) {\n")
file(APPEND "${OUTPUT}" "    FpatchEmbeddedResource missing = {NULL, 0};\n    size_t i;\n")
file(APPEND "${OUTPUT}" "    for (i = 0; i < sizeof(fpatch_resources) / sizeof(fpatch_resources[0]); i++) {\n")
file(APPEND "${OUTPUT}" "        if (strcmp(fpatch_resources[i].kind, kind) == 0 && strcmp(fpatch_resources[i].name, name) == 0) {\n")
file(APPEND "${OUTPUT}" "            FpatchEmbeddedResource found = {fpatch_resources[i].data, fpatch_resources[i].size};\n            return found;\n        }\n    }\n    return missing;\n}\n")
